package:
  name: dmagic
  version: '0.0.4'

source:
  path: src
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
 
  run:
    - python

test:
  # Python imports
  imports:
    - dmagic

about:
  home: http://dmagic.readthedocs.org
  license: BSD-3
  summary: 'Data Management Magic Tools.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
